import type { Metadata } from "next";
import { SimulationReport } from "@/components/simulation-report";
import { WorkspaceShell } from "@/components/workspace-shell";
import { bilingual, chooseLocale } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/i18n-server";
import scenario from "@/lib/simulation-scenario.json";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getRequestLocale();
  return {
    title: chooseLocale(
      locale,
      "Illustrative investigation report",
      "完整调查报告样张",
    ),
    description: chooseLocale(
      locale,
      "A complete, truth-labelled example of the report produced after a multi-stage investigation.",
      "一份完整并明确标注真实性边界的多阶段调查报告样张。",
    ),
  };
}

export default function SimulationReportPage() {
  return (
    <WorkspaceShell
      activeStep="report"
      caseMetaOverride={bilingual(
        "Illustrative report · not generated by a live run",
        "完整报告样张 · 非实时调查产出",
      )}
      caseTitleOverride={bilingual(
        "Starbucks stores associated with Shanghai Jing'an Kerry Centre",
        scenario.subject,
      )}
      disclosureOverride={bilingual(
        "This is a prebuilt product specimen with 0 real evidence. It cannot be used for purchasing or operating decisions.",
        "这是包含 0 条真实证据的预制产品样张，不可用于采购或经营决策。",
      )}
      storageLabelOverride={bilingual(
        "Report sample · no evidence writes",
        "报告样张 · 不写入证据账本",
      )}
      title={bilingual(
        "Complete illustrative report.",
        "完整调查报告样张。",
      )}
      description={bilingual(
        "Read the executive finding, fact resolution, evidence matrix, method, source register, response logic, and persona appendix in one place.",
        "在一个页面中查看执行摘要、事实判断、证据矩阵、调查方法、来源登记、响应逻辑与人物附录。",
      )}
    >
      <SimulationReport />
    </WorkspaceShell>
  );
}
